In [1]:
import sys, pathlib
from pathlib import Path
import json
import ast
import pandas as pd

from crew import PersonalTrainers

from tools.prompt_cache import cached_call
from tools.prompt_preparator import prep_prompt_for_fetch_exercises, prep_prompt_for_select_exercises

ROOT = pathlib.Path.cwd()          
sys.path.append(str(ROOT))



def crew_pt(client_request: str, client_request_2 : str) -> str:
    inputs = {"user_request": client_request,
              "user_needs": client_request_2}
    result = PersonalTrainers().crew().kickoff(inputs=inputs).raw

    return result

In [2]:
# python workout_questionnaire.py easier

In [2]:
# Open workout payloat (used to simulate the payload that will arrive from the frontend)
file_path = Path("workout_payload.json")

with file_path.open("r", encoding="utf-8") as fp:
    payload = json.load(fp)

prompt_1 = prep_prompt_for_fetch_exercises(payload_orig=payload)

prompt_2 = prep_prompt_for_select_exercises(payload=payload)

In [8]:
payload

{'level': 'Intermediate',
 'train_target': 'Upper body',
 'focus_muscle': True,
 'muscles': ['Chest', 'Biceps'],
 'duration_minutes': 90,
 'location': 'Park',
 'equipment': ['Gymnastics rings', 'Pull-up bar', 'Parallel bars', 'Ground']}

In [3]:
print(prompt_1)

print(prompt_2)

    Select the exercises using these informations:
    - body_region: Upper body
        - muscles: Chest, Biceps
        - equipment: Gymnastics rings, Pull-up bar, Parallel bars, Ground
The user, with Intermediate experience, is looking for a/an Upper body training program focusing on the following muscles: ['Chest', 'Biceps']. The duration of the training program is 90 minutes

In [4]:
# Call CREW with cached call
filter_generated = cached_call(prompt_1, prompt_2, crew_pt)

# Format output during testing
data = ast.literal_eval(filter_generated)

In [5]:
final_program = pd.DataFrame(data.get('exercises'))
final_program

,name,movement_pattern,movement_type,body_region,load_class,muscles,equipments,prot_1,prot_2,prot_3
0,parallel bar dips,horizontal push,compound,upper body,bodyweight,"chest, shoulders, triceps","gymnastics rings, parallel bars",Straight Sets | 4 sets × 8 reps,AMRAP | 2 sets max reps,Drop Sets | 1 set × 8 reps +2×drops
1,pull ups,vertical pull,compound,upper body,bodyweight,"biceps, lats","gymnastics rings, pull-up bar",Reverse Pyramid | 3 sets 8-6-4 reps,AMRAP | 1 set max reps ≤ 8,5×5 Linear Progression | 5 sets 5 reps
2,push ups,horizontal push,compound,upper body,bodyweight,"chest, shoulders, triceps","ground, gymnastics rings, parallettes",Straight Sets | 4 sets × 8 reps,AMRAP | 2 sets max reps,Ascending Pyramid | 3 sets × 12-10-8 reps
3,australian pull ups,horizontal pull,compound,upper body,bodyweight,"biceps, lats","gymnastics rings, pull-up bar",EMOM | 10 min × 3-5 reps per minute,"Cluster Sets | 4 sets × (4×2 reps, :15 rest)",Straight Sets | 4 sets × 8 reps

In [8]:
print("The user, with Intermediate experience, is looking for a Full body training program \nfocusing on all the muscles presents in the selected exercises. \nThe duration of the training program is 120 minutes")


final_program[['name', 'equipments', 'muscles', 'prot_1', 'prot_2', 'prot_3']]

The user, with Intermediate experience, is looking for a Full body training program
focusing on all the muscles presents in the selected exercises.
The duration of the training program is 120 minutes

,name,equipments,muscles,prot_1,prot_2,prot_3
0,squat w,"barbell, kettlebell, smith machine","glutes, quads",5×5 Linear Progression | 5 sets 5 reps,Ascending Pyramid | 3 sets 12-10-8 reps,"Cluster Sets | 4 sets (4×2 reps, :15 rest)"
1,lunges w,"barbell, dumbbells, kettlebell","glutes, quads",Straight Sets | 4 sets 8 reps,Reverse Pyramid | 3 sets 8-6-4 reps,Drop Sets | 1 set 8 reps +2 drops
2,horizontal bench press,"barbell, dumbbells, smith machine","chest, shoulders, triceps",5×5 Linear Progression | 5 sets 5 reps,German Volume Training | 10 sets 10 reps,Wave Loading | 6 sets × 3 reps (e.g. 80-85-90 %)
3,barbell row,barbell,"biceps, lats",Reverse Pyramid | 3 sets 8-6-4 reps,"Cluster Sets | 4 sets (4×2 reps, :15 rest)",5×5 Linear Progression | 5 sets 5 reps
4,v-push ups,ground,"shoulders, triceps",AMRAP | 2 sets max reps,EMOM | 10 min × 3-5 reps per minute,Rest-Pause | 1 set max-reps +2×RP
5,pull ups,"gymnastics rings, pull-up bar","biceps, lats",Reverse Pyramid | 3 sets 8-6-4 reps,AMRAP | 1 set max reps ≤ 8,5×5 Linear Progression | 5 sets 5 reps