In [1]:
import sys, pathlib
from pathlib import Path
import json
import ast
import pandas as pd

from crew import PersonalTrainers

from tools.prompt_cache import cached_call
from tools.prompt_preparator import prep_prompt_for_fetch_exercises, prep_prompt_for_select_exercises

ROOT = pathlib.Path.cwd()          
sys.path.append(str(ROOT))



def crew_pt(client_request: str, client_request_2 : str) -> str:
    inputs = {"user_request": client_request,
              "user_needs": client_request_2}
    result = PersonalTrainers().crew().kickoff(inputs=inputs).raw

    return result

In [2]:
# python workout_questionnaire.py easier

In [3]:
# Open workout payloat (used to simulate the payload that will arrive from the frontend)
file_path = Path("workout_payload.json")

with file_path.open("r", encoding="utf-8") as fp:
    payload = json.load(fp)

prompt_1 = prep_prompt_for_fetch_exercises(payload=payload)

prompt_2 = prep_prompt_for_select_exercises(payload=payload)

In [4]:
print(prompt_1)

print(prompt_2)

    Select the exercises using these informations:
    - body_region: Upper body
The user, with Advanced experience, is looking for a/an Upper body training program focusing on all the muscles presents in the selected exercises. The duration of the training program is 120 minutes

In [7]:
# Call CREW with cached call
filter_generated = cached_call(prompt_1, prompt_2, crew_pt)

# Format output during testing
data = ast.literal_eval(filter_generated)

In [10]:
final_program = pd.DataFrame(data.get('exercises'))
final_program

,name,movement_pattern,movement_type,body_region,load_class,muscles,equipments,prot_1,prot_2,prot_3
0,horizontal bench press,horizontal push,compound,upper body,free-weight,"chest, shoulders, triceps","barbell, dumbbells, smith machine",5×5 Linear Progression | 5 sets 5 reps,Wave Loading | 6 sets 3 reps (e.g. 80-85-90 %),Rest-Pause | 1 set max-reps +2×RP
1,barbell row,horizontal pull,compound,upper body,free-weight,"biceps, lats",barbell,Reverse Pyramid | 3 sets 8-6-4 reps,5×5 Linear Progression | 5 sets 5 reps,EMOM | 10 min × 3-5 reps per minute
2,military press,vertical push,compound,upper body,free-weight,"shoulders, triceps","barbell, dumbbells, smith machine","Cluster Sets | 4 sets (4×2 reps, :15 rest)",5×5 Linear Progression | 5 sets 5 reps,Wave Loading | 6 sets 3 reps (e.g. 80-85-90 %)
3,lat pulldown,vertical pull,compound,upper body,machine,"biceps, lats",lat machine,German Volume Training | 10 sets 10 reps,Ascending Pyramid | 3 sets 12-10-8 reps,AMRAP | 2 sets max reps
4,chest fly w1,single-joint,isolation,upper body,machine,chest,mid cables,Straight Sets | 3 sets 12 reps,Drop Sets | 1 set 8 reps +2×drops,Rest-Pause | 1 set max-reps +2×RP
5,bicep curl w1,single-joint,isolation,upper body,free-weight,biceps,"barbell, dumbbells",Straight Sets | 3 sets 12 reps,Ascending Pyramid | 3 sets 12-10-8 reps,Rest-Pause | 1 set max-reps +2×RP

In [13]:
print("The user, with Advanced experience, is looking for a/an Upper body training program focusing on all the muscles presents in the selected exercises. \nThe duration of the training program is 120 minutes")


final_program[['name', 'muscles', 'prot_1', 'prot_2', 'prot_3']]

The user, with Advanced experience, is looking for a/an Upper body training program focusing on all the muscles presents in the selected exercises.
The duration of the training program is 120 minutes

,name,muscles,prot_1,prot_2,prot_3
0,horizontal bench press,"chest, shoulders, triceps",5×5 Linear Progression | 5 sets 5 reps,Wave Loading | 6 sets 3 reps (e.g. 80-85-90 %),Rest-Pause | 1 set max-reps +2×RP
1,barbell row,"biceps, lats",Reverse Pyramid | 3 sets 8-6-4 reps,5×5 Linear Progression | 5 sets 5 reps,EMOM | 10 min × 3-5 reps per minute
2,military press,"shoulders, triceps","Cluster Sets | 4 sets (4×2 reps, :15 rest)",5×5 Linear Progression | 5 sets 5 reps,Wave Loading | 6 sets 3 reps (e.g. 80-85-90 %)
3,lat pulldown,"biceps, lats",German Volume Training | 10 sets 10 reps,Ascending Pyramid | 3 sets 12-10-8 reps,AMRAP | 2 sets max reps
4,chest fly w1,chest,Straight Sets | 3 sets 12 reps,Drop Sets | 1 set 8 reps +2×drops,Rest-Pause | 1 set max-reps +2×RP
5,bicep curl w1,biceps,Straight Sets | 3 sets 12 reps,Ascending Pyramid | 3 sets 12-10-8 reps,Rest-Pause | 1 set max-reps +2×RP